project:
  type: website
  render: 
    - "00-welcome-page.qmd"
    - "01-reprores-slides.qmd"
    - "02-further-reads.qmd"
    - "!templates/"

execute:
  freeze: auto # computational documents re-render only when source changes

website: 
  title: "Reproducible research"
  navbar: 
    left: 
      - text: Welcome
        href: 00-welcome-page.qmd
      - text: Slides
        href: 01-reprores-slides.qmd
      - text: Resources
        href: 02-further-reads.qmd
    tools:
      - icon: github
        text: Source Code
        href: https://github.com/ellfran-7/repro-research-student-seminar-lbbe
  page-footer: 
    left: "Â© Ellis Franklin, 2026."
    right: "Made with ðŸ’š and Quarto"

format:
  html:
    toc: true
    theme: [minty, web-styles.scss]
    grid: 
      body-width: 1000px
    



